# Generated by Django 4.2.1 on 2023-07-02 19:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_managers_user_date_joined_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.RegexValidator(inverse_match=True, message='Почта не должна быть rambler.ru', regex='rambler.ru')]),
        ),
    ]
